### ISSUE TITLE
Fix overflow on monthly history table when using mobile

### ISSUE THREAD

**Issue by pafnow** [ssenart/lovelace-gazpar-card#13]
Hi again,

I notice that when I open the card with the mobile application, the monthly history table is truncated on the right (which contains the last/current months) as seen below
![image](https://user-images.githubusercontent.com/8747037/197162754-080b1dce-5475-435f-bd93-1b1e46ce1ab1.png)
You cannot see September + October.

Would it be possible to change the overflow css property on week-history class from hidden to scroll (or something similar).
Expected result is to have an horizontal scrollbar:
![image](https://user-images.githubusercontent.com/8747037/197163562-2be00a1f-0f26-41fa-b510-adcacaed4cd7.png)

Thanks

**Comment by ssenart** [comment]
Thanks, indeed, I will fix that shortly.

**Comment by ssenart** [comment]
I have fixed that in 1.3.3. 
I choose to reduce the font size.
It works with my phone.

**Comment by pafnow** [comment]
Still truncated on mine (Mi9 not the smallest one)
![Screenshot_2022-10-22-08-29-42-731_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/8747037/197324069-17a8560c-9eed-4cfd-afdf-e69f2f1b798e.jpg)

**Comment by ssenart** [comment]
You still have 3 options:
- First, you can try to zoom out. There is an option in HA app companion general settings.
-  Or, you remove the first header column of the table. There is a toggle in the card config for that.
- You also can control the text size at the phone settings.

Let me know which one works best !

**Comment by pafnow** [comment]
Sorry for the delay, I have removed the first  column header 
Thanks
