### ISSUE TITLE
[Bug] No graph with Firefox

### ISSUE THREAD

**Issue by nicolas-r** [ssenart/lovelace-gazpar-card#14]
Hi

many thanks for your card.

With the HA application on IOs or Edge on Windows I can see the graphics. But with Firefox on Windows, I don't see them

In the Firefox web tools, I can see some errors related to chart.min.js, for example

Uncaught (in promise) Error: Canvas is already in use. Chart with ID '0' must be destroyed before the canvas with ID 'monthlyEnergyHistoryChart' can be reused.
    bn chart.min.js:13
    updateMonthlyEnergyChart gazpar-card.js:115
    updated gazpar-card.js:101
    _$AE app.d6aee905.js:1249
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    value cebaf2eb.js:369
    _$AE app.d6aee905.js:1249
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    k app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    m app.d6aee905.js:1249
    T app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    S app.d6aee905.js:1249
    update app.d6aee905.js:1249
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    value app-drawer-layout.js:189
    value hass-loading-screen.ts:11
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    k app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    m app.d6aee905.js:1249
    T app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    S app.d6aee905.js:1249
    update app.d6aee905.js:1249
chart.min.js:13:87572
    _$EC app.d6aee905.js:1249
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    value hui-masonry-view.ts:44
    forEach self-hosted:203
    value hui-masonry-view.ts:44
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    value cebaf2eb.js:369
    _$AE app.d6aee905.js:1249
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    k app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    m app.d6aee905.js:1249
    T app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    S app.d6aee905.js:1249
    update app.d6aee905.js:1249
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    value app-drawer-layout.js:189
    value hass-loading-screen.ts:11
    performUpdate app.d6aee905.js:1249
    scheduleUpdate app.d6aee905.js:1249
    _$EC app.d6aee905.js:1249
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    requestUpdate app.d6aee905.js:1249
    set app.d6aee905.js:1249
    k app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    m app.d6aee905.js:1249
    T app.d6aee905.js:1249
    _$AI app.d6aee905.js:1249
    S app.d6aee905.js:1249
    update app.d6aee905.js:1249
Error: Promised response from onMessage listener went out of scope ExtensionMessagingService.js:89:34

I don't know if this related to my brower setup or not

Nicolas

**Comment by ssenart** [comment]
Hi, indeed, after upgrading my old firefox version 97 to the latest 106, I also have some error messages and the charts are not displayed anymore. I don't know yet why...

**Comment by ssenart** [comment]
Hello, in fact, I don't have your error in Firefox but another one:

```text
Uncaught (in promise) :
columnNumber: 0
data: null
filename: "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"
lineNumber: 13
message: ""
name: "NS_ERROR_FAILURE"
result: 2147500037
stack: "fit@https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js:13:145008\nupdate@https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js:13:144351\nqi@https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js:13:35179\nupdate@
...
```

And it seems to be related to a bug in Firefox in very specific conditions: https://bugzilla.mozilla.org/show_bug.cgi?id=941146

I don't find any workaround.
