### ISSUE TITLE
[Bug] Valeur change sur le dashboard aléatoirement

### ISSUE THREAD

**Issue by skawsk** [ssenart/lovelace-gazpar-card#15]
Bonjour, et d'abord merci pour cette intégration :)

Je rencontre un problème étrange.
Les données affichées varient quand j'actualise ma page, elle passe du 02/11/2022 au 20/10/2022 à chaque rafraichissement de la page.
Je constate aussi le problème à chaque édition d'une option de la carte

Avez-vous déjà rencontré ce soucis ?

Exemple ici ou j'active/désactive l'option "Show monthly cost history chart"

![image](https://user-images.githubusercontent.com/74474945/200024812-c2cbb945-0cb9-4cb2-a8ea-1d88971469c1.png)
![image](https://user-images.githubusercontent.com/74474945/200024859-58390907-f0db-4a93-aa73-910b247e9899.png)

**Comment by ssenart** [comment]
Bonjour, oui, je constate ça aussi sur le panel de configuration. Je ne sais pas comment ce comportement arrive.

Par contre, sur le dashboard, tout est en ordre et correct.

Peux-tu essayer de vider le cache du navigateur et rafraichir ton dashboard à nouveau ?

Qual navigateur utilises-tu ?

**Comment by skawsk** [comment]
Bonjour je suis sous Google Chrome mais même constat sur l'application Home Assistant 

Sur mon dashboard j'ai aussi la même chose car je l'ai ajouté comme menu sur un bouton de mon interface, à chaque ouverture/fermeture, le problème survient 😬

 [https://user-images.githubusercontent.com/74474945/200094256-aa76dae8-5178-4980-a2c7-730d5ff10382.MOV]()

**Comment by herveaurel** [comment]
> Bonjour, et d'abord merci pour cette intégration :)
> 
> Je rencontre un problème étrange. Les données affichées varient quand j'actualise ma page, elle passe du 02/11/2022 au 20/10/2022 à chaque rafraichissement de la page. Je constate aussi le problème à chaque édition d'une option de la carte
> 
> Avez-vous déjà rencontré ce soucis ?
> 
> Exemple ici ou j'active/désactive l'option "Afficher l'historique des coûts mensuels"
> 
> ![image](https://user-images.githubusercontent.com/74474945/200024812-c2cbb945-0cb9-4cb2-a8ea-1d88971469c1.png) ![image](https://user-images.githubusercontent.com/74474945/200024859-58390907-f0db-4a93-aa73-910b247e9899.png)

Meme soucis 😉

**Comment by ssenart** [comment]
Oui, il doit y avoir un bug. Je vais investiguer... merci pour m'avoir remonter ce problème.

**Comment by ssenart** [comment]
Hello, je pense avoir fixé le problème dans la version 1.3.4. Pouvez-vous me confirmer que c'est bon dans tous vos cas d'utilisation où le problème apparaît ?

**Comment by herveaurel** [comment]
> Hello, je pense avoir fixé le problème dans la version 1.3.4. Pouvez-vous me confirmer que c'est bon dans tous vos cas d'utilisation où le problème apparaît ?

Je teste et je reviens vers toi. 
Merci pour tout.

**Comment by herveaurel** [comment]
> Hello, je pense avoir fixé le problème dans la version 1.3.4. Pouvez-vous me confirmer que c'est bon dans tous vos cas d'utilisation où le problème apparaît ?

J'ai l'impression que ton correctif a fonctionné !

**Comment by herveaurel** [comment]
> Hello, je pense avoir fixé le problème dans la version 1.3.4. Pouvez-vous me confirmer que c'est bon dans tous vos cas d'utilisation où le problème apparaît ?

Arf navré. Les valeurs viennent de délirer encore ... 🙁

**Comment by ssenart** [comment]
As-tu bien vidé le cache de ton navigateur ? Sinon, il va utiliser de façon certaine l'ancienne version.

**Comment by herveaurel** [comment]
> As-tu bien vidé le cache de ton navigateur ? Sinon, il va utiliser de façon certaine l'ancienne version.

Oui, également dans l'app mobile.

**Comment by herveaurel** [comment]
> As-tu bien vidé le cache de ton navigateur ? Sinon, il va utiliser de façon certaine l'ancienne version.

A suivre mais sur pc ça semble se maintenir. 

Sur cette capture où je scinde le tableau, je n'avais jamais les mêmes valeurs. ![image](https://user-images.githubusercontent.com/64784541/200180267-bc324ff3-3221-4667-b744-88e318e4c84f.jpeg)

**Comment by skawsk** [comment]
Bonjour je confirme que j'ai toujours le problème avec l'application Home Assistant 

Sur PC ça semble fonctionner également

**Comment by herveaurel** [comment]
De mon côté les valeurs sont stables sur pc.

**Comment by skawsk** [comment]
Oui idem sur pc juste sur mobile malgré purge du cache et j'ai même essayé de me déconnecter reconnecter sans succès

![image](https://user-images.githubusercontent.com/74474945/200371847-4edd3d13-71fd-4a0b-9adb-76e662971034.png)
![image](https://user-images.githubusercontent.com/74474945/200371865-6135b29d-c467-4b6b-b356-57fe8e2d4346.png)

**Comment by ssenart** [comment]
C'est Andoid ou IOS ?

**Comment by skawsk** [comment]
iOS pour moi

**Comment by ssenart** [comment]
Tu fais comment pour purger le cache de l'app Home Assistant sous IOS ?

**Comment by skawsk** [comment]
Je vais dans Paramètres > Application Compagnon > Debogage >  Réinitialiser le cache Front End

**Comment by ssenart** [comment]
Je suis aussi sur IOS, et je n'ai pas eu ce pb.

Je vois aussi sur tes captures que l'ordre des mois est inversé. Alors ça !

**Comment by ssenart** [comment]
Et si tu affiches les graphes de conso, tu as aussi cette inversion ?

**Comment by herveaurel** [comment]
iOS j'ai le soucis également. 
Pas sur Mac.

**Comment by ssenart** [comment]
Pour éliminer totalement cette histoire de cache, je pourrais vous demander de résintaller l'app HA. Comme vous voulez...

Je n'ai aucune autre idée pour l'instant.

**Comment by skawsk** [comment]
Re,
J'ai désinstallé via HACS.
J'ai purgé mon cache via le debogage de l'application et j'ai réinstallé mais le problème est toujours présent :/

Il y a des fichiers à purger après la désinstallation ?

**Comment by herveaurel** [comment]
Ce n'est pas un soucis de l'intégration car sur pc il n'y a pas de soucis. 
Soit un cache de l'app, mais apparement nous le supprimons de la même manière donc j'y crois pas. 
Soit un bug de l'app iOS selon moi.

**Comment by ssenart** [comment]
Bon, je vais rajouter un numéro de version dans la carte pour vérifier quel code est vraiment chargé. Ca ne corrigera rien, mais au moins on saura si c'est le code qui est en cause ou bien la nouvelle qui n'est pas chargée.

**Comment by herveaurel** [comment]
Très bonne idée ! 
(Et encore merci pour tout le taf)

**Comment by ssenart** [comment]
Bien, rajouter la version m'a permis de voir que le problème venait du code et pas du cache.

Du coup, j'ai corrigé (difficile car visible que sous IOS) et j'ai testé avec succès sur l'app HA, sur Chrome et sur Safari.

Je n'attend plus que votre validation ;-) de la version 1.3.5 avec le fixe.

Et n'oublier pas de vider le cache après la mise à jour. J'ai pu vérifier que cela fonctionne bien et que c'est indispensable.

**Comment by herveaurel** [comment]
Très bonne nouvelle ! 
De mon côté pas de MàJ proposée pour l'instant....

**Comment by skawsk** [comment]
Je confirme de mon côté ça fonctionne :)

**Comment by skawsk** [comment]
#@herveaurel j'ai retelechargé via HACS, ça ne me proposait pas de nivelle version non plus mais la 1.3.5 est disponible

**Comment by herveaurel** [comment]
> Bien, rajouter la version m'a permis de voir que le problème venait du code et pas du cache.
> 
> 
> 
> Du coup, j'ai corrigé (difficile car visible que sous IOS) et j'ai testé avec succès sur l'app HA, sur Chrome et sur Safari.
> 
> 
> 
> Je n'attend plus que votre validation ;-) de la version 1.3.5 avec le fixe.
> 
> 
> 
> Et n'oublier pas de vider le cache après la mise à jour. J'ai pu vérifier que cela fonctionne bien et que c'est indispensable.

MERCI !!!!!

**Comment by ssenart** [comment]
Il me semble que ce problème est fixé.
