### ISSUE TITLE
1.3.5 regression: Display issues when data is uncommon

### ISSUE THREAD

**Issue by pafnow** [ssenart/lovelace-gazpar-card#17]
Related to https://github.com/ssenart/lovelace-gazpar-card/issues/10

Until 1.3.4 everything was working fine but the last version you released (1.3.5) make the old problem back.

![image](https://user-images.githubusercontent.com/8747037/200562520-4a45a173-6166-46fa-9f01-6b51eb1852b8.png)

**Comment by ssenart** [comment]
oops, sorry, I made a wrong copy/paste in the code, and it broke your use case. I fix that tonight.

**Comment by ssenart** [comment]
fixed with 1.3.6 and sorry again !

Do you confirm ?

**Comment by pafnow** [comment]
Yes confirmed, thanks for your fast action
