### ISSUE TITLE
[Bug] Cropped information

### ISSUE THREAD

**Issue by herveaurel** [ssenart/lovelace-gazpar-card#19]
Hello, since the last update of the map, consumption is cropped as on the screen
<img width="539" alt="Capture d’écran 2022-11-27 à 10 54 50" src="https://user-images.githubusercontent.com/64784541/204129319-476a6076-16bf-4865-a221-87d23d0e08e7.png">

**Comment by ssenart** [comment]
Hello, it means Grdf data are not yet available for those dates. You can confirm that by going on their site on "Mon espace".

**Comment by herveaurel** [comment]
> Hello, it means Grdf data are not yet available for those dates. You can confirm that by going on their site on "Mon espace".

Je ne parle pas des conso indisponibles, mais de la valeur en haut qui est rognée. Meme quand les mise a jour etaient operationnelles, la valeur est tronquée en haut, depuis la derniere mise a jour

**Comment by ssenart** [comment]
Ah, oui, pardon. Oui, en effet, j'arrive à la reproduire en retirant l'icône (optionnel) de Gazpar. Je vais fixer dans la semaine. Merci !

**Comment by herveaurel** [comment]
> Ah, oui, pardon. Oui, en effet, j'arrive à la reproduire en retirant l'icône (optionnel) de Gazpar. Je vais fixer dans la semaine. Merci !

Merci beaucoup, en francais c'était plus simple 😆

**Comment by herveaurel** [comment]
Par contre, dans mon espace de grdf tout est nickel, donc je ne vois pas pourquoi les remontées ne se font plus...

**Comment by ssenart** [comment]
C'est à dire ? De quand date tes dernières données à jour sur le site GrDF ? Regarde bien les dates et les quantités en comparaison de la carte.

Pour ma part, je n'ai plus de mise à jour depuis mardi dernier. J'ai aussi 4 colonnes vides dans la carte. Et lorsque je vais sur le site, il manque aussi 4 jours de consos et la dernière remonte aussi au 22/11 et les quantités correspondent.

**Comment by herveaurel** [comment]
Tu as raison. En fait j'ai comme toi ...

**Comment by ssenart** [comment]
Hello, c'est livré en 1.3.8. En parallèle, je travaille pour rétablir l'alimentation en données. Tu peux suivre le sujet ici: https://github.com/ssenart/home-assistant-gazpar/issues/28

**Comment by herveaurel** [comment]
Merci, j'ai vu ca 😉

**Comment by herveaurel** [comment]
C'est mieux mais c'est pas encore parfait ! 😅

**Comment by ssenart** [comment]
c'est comment ?

**Comment by ssenart** [comment]
Ah, oui, sur Edge et Firefox, c'est tjrs coupé. Je suis sur Chrome.

Bon, je vais revoir ma copie.

**Comment by ssenart** [comment]
Ah, je n'avais pas rafraichi le cache dans Edge et Firefox, du coup, j'avais l'ancienne version. Maintenant, c'est ok pour les 3 navigateurs et sur mon téléphone.

Quel navigateur utilises-tu ?

As-tu bien rafraichi ton cache ? 

Affiche le numéro de version de la carte et vérifie que c'est bien la 1.3.8.

**Comment by herveaurel** [comment]
Je suis sous chrome et safari. 
Et app iPhone. 
Identique partout. Légèrement coupé encore en haut. ![image](https://user-images.githubusercontent.com/64784541/206015152-eaabe019-4116-46a8-9e80-0a6086045266.png)

**Comment by ssenart** [comment]
Et si tu retires le bandeau "Gaz - 5.64€ abo inclus" ? D'ailleurs comment tu fais ça ? Tu mets plusieurs cartes dans une seule ?

Chez moi, j'ai ça. C'est à dire la carte seule dans son emplacement:

![image](https://user-images.githubusercontent.com/37013755/206016216-8fdfb5eb-6533-4a1f-bd70-062b1a7085b5.png)

**Comment by ssenart** [comment]
La 1.3.9-alpha.1 est pour toi !

**Comment by herveaurel** [comment]
🤣
J'installe dès qu'elle apparaît ! 
Merci

**Comment by herveaurel** [comment]
> La 1.3.9-alpha.1 est pour toi !

Tout est ok 👍🏼 
Merci ! 😉
