### ISSUE TITLE
[Bug] Error message too long

### ISSUE THREAD

**Issue by herveaurel** [ssenart/lovelace-gazpar-card#22]
Bonjour. 
Simplement pour signaler que certains messages d'erreurs sont longs... très longs... et mettent à mal tout le Dashboard ! 🤣

Une capture sera mieux que des explications... 😅

<img width="606" alt="image" src="https://user-images.githubusercontent.com/64784541/204247190-5b51e49f-6908-443a-b5cb-d8aff3d7f1a3.png">

**Comment by ssenart** [comment]
Bonjour, oui en effet, je vais le raccourcir à l'essentiel. Pour le détail, il faudra aller voir dans la log.
