### ISSUE TITLE
[Bug] January month disappear, December appears twice

### ISSUE THREAD

**Issue by pafnow** [ssenart/lovelace-gazpar-card#27]
Happy New Year,

I'm back with a new strange things on this wonderful card.

![image](https://user-images.githubusercontent.com/8747037/210213980-19e35e64-3273-43ce-b536-9adf2b822841.png)

As you can see, the january month is not shown, but there are twice D for December.
The comparison with December data is made on both double D columns.
This problem already happen since last week at least, didn't had time to post it sooner.

Let me know if you need anything else

**Comment by ssenart** [comment]
Thanks and best wishes !

It should be fixed in [1.3.5-alpha1](https://github.com/ssenart/home-assistant-gazpar/releases/tag/1.3.5-alpha.1) (actually in alpha.0) of home-assistant-gazpar.

Try this and tell me !

**Comment by pafnow** [comment]
I'm running 1.3.9
![image](https://user-images.githubusercontent.com/8747037/210236913-e72db936-47c2-4b59-bb7b-d98372fdce7f.png)

**Comment by ssenart** [comment]
Here, you are displaying the version the card, not the integration.
I meant [1.3.5-alpha1](https://github.com/ssenart/home-assistant-gazpar/releases/tag/1.3.5-alpha.1) of the integration home-assistant-gazpar. You have to upgrade the version of the integration.
You don't have to change the version of the card.

**Comment by pafnow** [comment]
Thanks for the precision,
it works properly now indeed.
Thanks
