### ISSUE TITLE
2 'D' month till 04/01

### ISSUE THREAD

**Issue by Gonioul** [ssenart/lovelace-gazpar-card#28]
Sorry, didn't take a screenshot, but the card had 2 'D' months instead of a 'D' and 'J' month until tonight.
Some side effect I guess.

**Comment by ssenart** [comment]
Is it the same as https://github.com/ssenart/lovelace-gazpar-card/issues/27 ?

**Comment by Gonioul** [comment]
Sorry, looks similar.
