### ISSUE TITLE
Can't see the repo in HACS

### ISSUE THREAD

**Issue by Patbonamy** [ssenart/lovelace-gazpar-card#31]
I have a problem with the card few days ago, it's stop working,not displaying.
I uninstall the repo and delete it, I try to add it again but don't see it's in the list but still's in the repo.
After reboot the plugin disappeared from the repo.
Help please.
Pat

**Comment by ssenart** [comment]
The problem you have with your card may be related to this one: https://github.com/ssenart/home-assistant-gazpar/issues/41

For the visibility of the plugin in HACS, be sure to go through the installation method 1 in the description here: https://github.com/ssenart/lovelace-gazpar-card/blob/main/README.md
