### ISSUE TITLE
Cost missing

### ISSUE THREAD

**Issue by Kri72** [ssenart/lovelace-gazpar-card#32]
Hello, now that the  Gazpar integration is working again 😄,  l reinstalled it, but have an issue with this Lovelace card.. it appears differently with two entities and no cost.. why clue on what is going wrong? 
![Screenshot_20240510_202718_Home Assistant.jpg](https://github.com/ssenart/lovelace-gazpar-card/assets/91803162/9dc30f96-8270-4180-8ef0-fb24bbf20031)

**Comment by ssenart** [comment]
Hello, yes, indeed, I have had also this rendering at the first installation.

I don't know what was going wrong.

As a workaround, I click on the button "Show code editor" on the bottom left and edit the configuration manually using the code:

```
type: custom:gazpar-card

entity: sensor.gazpar
title: Données GrDF
pricePerKWh: '0.06072'

showIcon: true
showTitle: true
showMainBar: true
showCost: true

showDailyHistory: true
showMonthlyHistory: true
showHistoryHeader: true
showEnergyHistory: true
showVolumeHistory: true
showTrendRatioHistory: true
showCostHistory: true

showDailyCostHistoryChart: false
showDailyEnergyHistoryChart: false

showWeeklyEnergyHistoryChart: false
showWeeklyCostHistoryChart: false

showMonthlyEnergyHistoryChart: false
showMonthlyCostHistoryChart: false

showYearlyEnergyHistoryChart: false
showYearlyCostHistoryChart: false

showError: true
showVersion: true
```

**Comment by ScratMan** [comment]
Hello, it seems the cost is fixed through the `pricePerKWh` parameter, but then it's fixed for all years, am I correct? 
Is it possible to use the total cost history from gazpar2haws instead?
