### ISSUE TITLE
ne peux avoir 1 carte dans un nouvel onglets 

### ISSUE THREAD

**Issue by enthalpie91** [ssenart/lovelace-gazpar-card#36]
bonjour
j'ai la carte gazpar dans l'onglet tableau de bord et je veux mettre une autre carte , qui n'affichera pas les même valeurs dans un autre onglet 
et là j'ai un message d'erreur comme quoi l'identity gazpar n'est pas défini alors que j'ai bien cela dans le fichier de configuration
![Screenshot_20241010_125726](https://github.com/user-attachments/assets/6301a335-e84a-413a-9323-bf680af9c3ca)
![Screenshot_20241010_125900](https://github.com/user-attachments/assets/36bab763-f0c3-4ac1-91ad-765c069de877)

**Comment by ssenart** [comment]
Hello, dans ta configuration, il manque:

```
entity: sensor.gazpar
```

**Comment by enthalpie91** [comment]
hello
je ne pensais pas qu'il fallait ajouter cette entrée
merci
