### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alban4github** [ssenart/lovelace-gazpar-card#4]
Hi

I currently have the Gazpar module (installed from HACS).
I've tried to set up the lovelace gazpar card but I get 
![image](https://user-images.githubusercontent.com/6586083/195559208-dcd4b141-06a5-45a9-aae6-5d29e027035c.png)

what did I miss ?

thx for the work
Al

**Comment by ssenart** [comment]
Hello, you did not miss anything. The combo Entity is not displayed in dialog (I already observed that). 

As a workaround, go through the manual config by clicking on "Afficher l'éditeur de code" and add the line :

entity: sensor.gazpar

Also, be sure that your integration Gazpar has been updated to version 1.2.0.

Let me know your progress...

**Comment by ssenart** [comment]
Hello, I have fixed the configuration editor panel. The entity text field is now showing up.

Let me know whether it is fixed on your side as well.

**Comment by alban4github** [comment]
Hello, it is working far better :-)
![image](https://user-images.githubusercontent.com/6586083/195789111-af5fdc50-99b1-41f9-8d11-bb8d754cd276.png)

2 comments:
- for the price of gaz kwh equivalent, it does not respect the regional for numbers, eg I had to seize 0.09 instead of 0,09 (my system is in french). this can be distubing
- it is a bit confusing, yesterday I had consumption figures for Wednesday and Thrusday ... but not this morning (Friday). kind of odd.
Thx again for this very nice work :-)

**Comment by ssenart** [comment]
Great news !

You're right, I'm not strict with regional settings:
- numbers are displayed with dot as decimal separator.
- i force month/weekdays in french.
I should rely on system config instead
I will try to improve this.

Yesterday, after installing the new version, did you clear your browser cache ? If not, you may experience some weird behaviour like you had. Or perhaps, you were facing a bug, and you will have it again in the future. Please, don't hesite to report it if it appears again !
